version: 0.1.0.{build}
image: WMF 5

install:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - ps: | 
        Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force
        Install-Module -Name Pester -Force
    - npm install -g gulp    
    - npm install  

build_script:
    - npm run build

test_script:
    - npm run test
    - ps: | 
        $webClient = New-Object -TypeName "System.Net.WebClient" 

        Start-Process -FilePath "$env:APPVEYOR_BUILD_FOLDER\node_modules\.bin\mocha" -ArgumentList "Tests\JavaScript --reporter mocha-junit-reporter --reporter-options mochaFile=mocharesults.xml" -Wait
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/junit/$($env:APPVEYOR_JOB_ID)", 
                                "$env:APPVEYOR_BUILD_FOLDER\mocharesults.xml")

        $testResultsFile = ".\TestsResults.xml"
        $testsPath = Join-Path -Path $env:APPVEYOR_BUILD_FOLDER `
                               -ChildPath "Tests\PowerShell"
        $testCoverageFiles = @()
        Get-ChildItem "$env:APPVEYOR_BUILD_FOLDER\modules\DSCStudio\*.psm1" -Recurse | ForEach-Object -Process { 
            $testCoverageFiles += $_.FullName    
        } 
        $result = Invoke-Pester -Path $testsPath -CodeCoverage $testCoverageFiles -OutputFormat "NUnitXml" -OutputFile $testResultsFile -PassThru

        $testResultsFilePath = Resolve-Path -Path $testResultsFile
        $webClient.UploadFile("https://ci.appveyor.com/api/testresults/nunit/$($env:APPVEYOR_JOB_ID)", 
                                $testResultsFilePath)

        if ($result.FailedCount -gt 0) 
        { 
            throw "$($result.FailedCount) tests failed."
        }
