version: 0.1.0.{build}
image: WMF 5

install:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - npm install -g gulp    
    - npm install  

build_script:
    - npm run build

test_script:
    - npm run test


