version: 0.1.0.{build}
image: WMF 5

install:
    - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
    - ps: | 
        Import-Module "$env:APPVEYOR_BUILD_FOLDER\Build\appveyortasks.psm1"
        Start-InstallTasks  
    - npm install

build_script:
    - npm run build

test_script:
    - npm run test
    - ps: |
        Start-TestTasks

after_test:
    - ps: |
        Start-PackageTasks
